### ISSUE TITLE
radio buttons are not working

### ISSUE THREAD

**Issue by KedarKK1** [PISB-Backend-SIGs/Frontend-SIGs#1]
give each radio button field same name, only their value should be different. Those values will be sent to backend whenever this form will be sent with their name as key and their value as value. This was told in 1st SIG.
 
You can also use textfield with predefined colums say 10.

Great efforts 🎉🎊, keep it up👍

**Comment by sarthakp10** [comment]
Resolved the radio button issue. It should be working now. Thanks for informing!!!
